config/routes.rb
Rails.application.routes.draw do
  get 'site/home'

  get 'site/about'

  get 'site/contact'

  resources :wines
  resources :vineyards
  resources :profiles
  devise_for :users
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  post "/wines/get_barcode" => "wines#get_barcode"
  root :to => "site#home"
  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  get '/home' => 'site#home'
end

app/models/vineyard.rb
class Vineyard < ApplicationRecord
  belongs_to :user
  mount_uploader :image_url, ImageUploader
end

app/controllers/vineyards_controller.rb
class VineyardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_vineyard, only: [:show, :edit, :update, :destroy]

  # GET /vineyards
  # GET /vineyards.json
  def index
    #@vineyards = Vineyard.all
    @user = User.find(current_user.id)
    @vineyards = @user.vineyards
  end

  # GET /vineyards/1
  # GET /vineyards/1.json
  def show
  end

  # GET /vineyards/new
  def new
    @vineyard = Vineyard.new
    @vineyard.user_id = current_user.id
  end

  # GET /vineyards/1/edit
  def edit
  end

  # POST /vineyards
  # POST /vineyards.json
  def create
    @vineyard = Vineyard.new(vineyard_params)

    respond_to do |format|
      if @vineyard.save
        format.html { redirect_to @vineyard, notice: 'Vineyard was successfully created.' }
        format.json { render :show, status: :created, location: @vineyard }
      else
        format.html { render :new }
        format.json { render json: @vineyard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vineyards/1
  # PATCH/PUT /vineyards/1.json
  def update
    respond_to do |format|
      if @vineyard.update(vineyard_params)
        format.html { redirect_to @vineyard, notice: 'Vineyard was successfully updated.' }
        format.json { render :show, status: :ok, location: @vineyard }
      else
        format.html { render :edit }
        format.json { render json: @vineyard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vineyards/1
  # DELETE /vineyards/1.json
  def destroy
    @vineyard.destroy
    respond_to do |format|
      format.html { redirect_to vineyards_url, notice: 'Vineyard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vineyard
      @vineyard = Vineyard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vineyard_params
      params.require(:vineyard).permit(:name, :type_vineyard, :image_url, :user_id, :user_id)
    end
end

app/helpers/vineyards_helper.rb
module VineyardsHelper
end

app/views/vineyards/_form.html.erb
<%= form_for(vineyard) do |f| %>
  <% if vineyard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vineyard.errors.count, "error") %> prohibited this vineyard from being saved:</h2>

      <ul>
      <% vineyard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :type_vineyard %>
    <%= f.text_field :type_vineyard %>
  </div>

  <div class="field">
    <%= f.file_field :image_url  %>  
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vineyards/edit.html.erb
<h1>Editing Vineyard</h1>

<%= render 'form', vineyard: @vineyard %>

<%= link_to 'Show', @vineyard %> |
<%= link_to 'Back', vineyards_path %>

app/views/vineyards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vineyards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type vineyard</th>
      <th>Image url</th>
      <th>User</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vineyards.each do |vineyard| %>
      <tr>
        <td><%= vineyard.name %></td>
        <td><%= vineyard.type_vineyard %></td>
       <!-- <td><%= vineyard.image_url %></td>-->
        <td><%= image_tag vineyard.image_url %></td>
        <td><%= vineyard.user_id %></td>
        <td><%= vineyard.user %></td>
        <td><%= link_to 'Show', vineyard %></td>
        <td><%= link_to 'Edit', edit_vineyard_path(vineyard) %></td>
        <td><%= link_to 'Destroy', vineyard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vineyard', new_vineyard_path %>

app/views/vineyards/new.html.erb
<h1>New Vineyard</h1>

<%= render 'form', vineyard: @vineyard %>

<%= link_to 'Back', vineyards_path %>

app/views/vineyards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vineyard.name %>
</p>

<p>
  <strong>Type vineyard:</strong>
  <%= @vineyard.type_vineyard %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @vineyard.image_url %>
</p>

<p>
  <strong>User:</strong>
  <%#= @vineyard.user_id %>
  <%= image_tag @vineyard.image_url.thumb.url, :style => "width: 30px; height:50px"; %>
</p>

<p>
  <strong>User:</strong>
  <%= @vineyard.user %>
</p>

<%= link_to 'Edit', edit_vineyard_path(@vineyard) %> |
<%= link_to 'Back', vineyards_path %>