config/routes.rb
Rails.application.routes.draw do
  get 'site/home'

  get 'site/about'

  get 'site/contact'

  resources :wines
  resources :vineyards
  resources :profiles
  devise_for :users
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  post "/wines/get_barcode" => "wines#get_barcode"
  root :to => "site#home"
  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  get '/home' => 'site#home'
end

app/models/wine.rb
class Wine < ApplicationRecord
  belongs_to :user
  belongs_to :vineyard
  mount_uploader :image_url, ImageUploader
  
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_wine, only: [:show, :edit, :update, :destroy]

  # GET /wines
  # GET /wines.json
  def index
    #@wines = Wine.all
    @user = User.find(current_user.id)
    @wines = @user.wines
  end

  # GET /wines/1
  # GET /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @user = User.find(current_user.id)
    @wine = @user.wines.build
    @wine.upc = params[:upc]
    #Wine.new
    #@wine.user_id = current_user.id
    @vineyard = @user.vineyards
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines
  # POST /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: 'Wine was successfully created.' }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

    # POST /products/get_barcode
  def get_barcode
     @user = User.find(current_user.id)
    @wine = @user.wines.find_or_initialize_by(upc: params[:upc])
    unless @wine.new_record?
      redirect_to @wine
    else
      redirect_to new_wine_path(upc: params[:upc])
    end
  end
  # PATCH/PUT /wines/1
  # PATCH/PUT /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: 'Wine was successfully updated.' }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: 'Wine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wine_params
      params.require(:wine).permit(:name, :type_wine, :image_url, :string, :country, :string, :wine_year, :upc, :rating, :vineyard_id, :user_id, :user_id, :vineyard_id)
    end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_form.html.erb
<%= form_for(wine) do |f| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :type_wine %>
    <%= f.text_field :type_wine %>
  </div>

  <div class="field">
    <% f.label :image_url %>
    <% f.text_field :image_url %>
    <%= f.file_field :userimage %>
  </div>

 

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

 

  <div class="field">
    <%= f.label :wine_year %>
    <%= f.number_field :wine_year %>
  </div>

  <div class="field">
    <%= f.label :upc %>
    
    <%# to display the barcode reader %>
    <div id='barcode-scanner'></div>
    <%= f.text_field :upc %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :vineyard_id %>
    <% options = options_from_collection_for_select(@vineyard, 'id', 'name') %>
    <%= f.select :vineyard_id, options %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
    $(function(){if($("#wine_upc").val()!='')
    {
        $("#barcode-scanner").hide();
        $("#barcode-scanner").prop("disabled",true);
    }
        });
    
</script>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type wine</th>
      <th>Image url</th>
      <th>String</th>
      <th>Country</th>
      <th>String</th>
      <th>Wine year</th>
      <th>Upc</th>
      <th>Rating</th>
      <th>Vineyard</th>
      <th>User</th>
      <th>User</th>
      <th>Vineyard</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td><%= wine.type_wine %></td>
        <td><%= image_tag wine.image_url %></td>
        <td><%#<%= wine.string %></td>
        <td><%= wine.country %></td>
        <td><%#<%= wine.string %></td>
        <td><%= wine.wine_year %></td>
        <td><%= wine.upc %></td>
        <td><%= wine.rating %></td>
        <td><%= wine.vineyard_id %></td>
        <td><%= link_to 'Show', wine%></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        
         <% if current_user.admin? %>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<p>
  <strong>Type wine:</strong>
  <%= @wine.type_wine %>
</p>

<p>
  <strong>Image url:</strong>
  <%= image_tag @wine.image_url %>
</p>


<p>
  <strong>Country:</strong>
  <%= @wine.country %>
</p>


<p>
  <strong>Wine year:</strong>
  <%= @wine.wine_year %>
</p>

<p>
  <strong>Upc:</strong>
  <%= @wine.upc %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @wine.rating %>
</p>

<p>
  <strong>Vineyard:</strong>
  <%= @wine.vineyard_id %>
</p>

<!--
<p>
  <strong>User:</strong>
  <%#= @wine.user_id %>
</p>

<p>
  <strong>User:</strong>
  <%#= @wine.user %>
</p>
-->
<p>
  <strong>Vineyard:</strong>
  <%= @wine.vineyard %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>